from django.core.exceptions import ValidationError


def {{ name }}(value):
    pass
