from django.core.exceptions import ValidationError


def {{ name }}_validator(value):
    pass
